import { Tournament, Player, MatchEvent, TacticalFormation, SportType } from '@/types/sports';

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'tour-fut-1',
    name: 'Copa Apertura Fútbol 7 & 6 - Torneo Central 2026',
    sport: 'futbol',
    category: 'Libre',
    format: 'Liga',
    status: 'active',
    startDate: '2026-10-01',
    endDate: '2026-11-28',
    location: 'Complejo Deportivo El Monumental, Campo Principal',
    description: 'Encuentros oficiales con alineaciones tácticas dinámicas y bolsa general de participantes.',
  },
  {
    id: 'tour-vol-1',
    name: 'Gran Circuito Interclubes Voleibol Pro 2026 (6 vs 6)',
    sport: 'voley',
    category: 'Mixto',
    format: 'Fase de Grupos',
    status: 'active',
    startDate: '2026-10-03',
    endDate: '2026-11-15',
    location: 'Coliseo Polideportivo Central, Cancha A Techada',
    description: 'Partidos de voleibol 6 vs 6 con rotaciones tácticas oficiales Z1 a Z6 y sets a 25 puntos.',
  },
];

export const INITIAL_PLAYERS: Player[] = [
  // Fútbol Players Pool
  {
    id: 'p-fut-1',
    name: 'Carlos Mendoza',
    phone: '+51 987 654 321',
    sport: 'futbol',
    position: 'Arquero (POR)',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 1,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 6, matchesWon: 5, goals: 0, assists: 1, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 2, ratingAverage: 4.9 },
  },
  {
    id: 'p-fut-2',
    name: 'Diego Salazar',
    phone: '+51 912 345 678',
    sport: 'futbol',
    position: 'Defensa Central (DFC)',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 4,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 6, matchesWon: 5, goals: 1, assists: 2, yellowCards: 1, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 0, ratingAverage: 4.4 },
  },
  {
    id: 'p-fut-3',
    name: 'Mateo Quispe',
    phone: '+51 999 888 777',
    sport: 'futbol',
    position: 'Lateral Derecho (LD)',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 2,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 5, matchesWon: 4, goals: 2, assists: 3, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.5 },
  },
  {
    id: 'p-fut-4',
    name: 'Rodrigo Benítez',
    phone: '+51 922 111 333',
    sport: 'futbol',
    position: 'Mediocampista Defensivo (MCD)',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 6,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 6, matchesWon: 5, goals: 3, assists: 5, yellowCards: 2, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.8 },
  },
  {
    id: 'p-fut-5',
    name: 'Gabriel Morales',
    phone: '+51 933 444 555',
    sport: 'futbol',
    position: 'Mediocampista Ofensivo (MCO)',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 10,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 6, matchesWon: 5, goals: 7, assists: 6, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 3, ratingAverage: 5.0 },
  },
  {
    id: 'p-fut-6',
    name: 'Lucas Fernández',
    phone: '+51 944 555 666',
    sport: 'futbol',
    position: 'Extremo Izquierdo (EI)',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 11,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 5, matchesWon: 4, goals: 4, assists: 4, yellowCards: 1, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.6 },
  },
  {
    id: 'p-fut-7',
    name: 'Franco Guerrero',
    phone: '+51 955 666 777',
    sport: 'futbol',
    position: 'Delantero Centro (DC)',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 9,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 6, matchesWon: 5, goals: 9, assists: 3, yellowCards: 1, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 2, ratingAverage: 4.9 },
  },
  {
    id: 'p-fut-8',
    name: 'Andrés Barreto',
    phone: '+51 966 777 888',
    sport: 'futbol',
    position: 'Arquero (POR)',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 1,
    isAvailable: true,
    createdAt: '2026-09-29',
    stats: { matchesPlayed: 5, matchesWon: 3, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.3 },
  },
  {
    id: 'p-fut-9',
    name: 'Esteban Cárdenas',
    phone: '+51 977 888 999',
    sport: 'futbol',
    position: 'Defensa Central (DFC)',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 5,
    isAvailable: true,
    createdAt: '2026-09-29',
    stats: { matchesPlayed: 5, matchesWon: 3, goals: 2, assists: 1, yellowCards: 3, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 0, ratingAverage: 4.1 },
  },
  {
    id: 'p-fut-10',
    name: 'Nicolás Palma',
    phone: '+51 988 999 000',
    sport: 'futbol',
    position: 'Volante Mixto (MC)',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 8,
    isAvailable: true,
    createdAt: '2026-09-29',
    stats: { matchesPlayed: 5, matchesWon: 3, goals: 3, assists: 4, yellowCards: 1, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.5 },
  },
  {
    id: 'p-fut-11',
    name: 'Samuel Rojas',
    phone: '+51 911 222 444',
    sport: 'futbol',
    position: 'Extremo Derecho (ED)',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 7,
    isAvailable: true,
    createdAt: '2026-09-29',
    stats: { matchesPlayed: 5, matchesWon: 3, goals: 4, assists: 2, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 0, ratingAverage: 4.2 },
  },
  {
    id: 'p-fut-12',
    name: 'Joaquín Paredes',
    phone: '+51 922 333 555',
    sport: 'futbol',
    position: 'Delantero Centro (DC)',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 9,
    isAvailable: true,
    createdAt: '2026-09-29',
    stats: { matchesPlayed: 5, matchesWon: 3, goals: 6, assists: 2, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.7 },
  },

  // Vóley Players Pool
  {
    id: 'p-vol-1',
    name: 'Valeria Rivas',
    phone: '+51 933 112 233',
    sport: 'voley',
    position: 'Armador / Colocador (S)',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 3,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 8, blocks: 3, effectiveAttacks: 12, mvpCount: 2, ratingAverage: 4.9 },
  },
  {
    id: 'p-vol-2',
    name: 'Camila Zúñiga',
    phone: '+51 944 223 344',
    sport: 'voley',
    position: 'Punta Receptor / Atacante (OH)',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 10,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 11, blocks: 5, effectiveAttacks: 34, mvpCount: 1, ratingAverage: 4.8 },
  },
  {
    id: 'p-vol-3',
    name: 'Renato Falconí',
    phone: '+51 955 334 455',
    sport: 'voley',
    position: 'Central / Bloqueador (MB)',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 7,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 4, blocks: 14, effectiveAttacks: 18, mvpCount: 0, ratingAverage: 4.6 },
  },
  {
    id: 'p-vol-4',
    name: 'Mauricio Paz',
    phone: '+51 966 445 566',
    sport: 'voley',
    position: 'Opuesto (OP)',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 9,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 9, blocks: 6, effectiveAttacks: 29, mvpCount: 1, ratingAverage: 4.7 },
  },
  {
    id: 'p-vol-5',
    name: 'Jimena Castro',
    phone: '+51 977 556 677',
    sport: 'voley',
    position: 'Líbero (L)',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 5,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 0, blocks: 0, effectiveAttacks: 0, mvpCount: 1, ratingAverage: 4.9 },
  },
  {
    id: 'p-vol-6',
    name: 'Bruno Arana',
    phone: '+51 988 667 788',
    sport: 'voley',
    position: 'Punta Receptor / Atacante (OH)',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 12,
    isAvailable: true,
    createdAt: '2026-09-27',
    stats: { matchesPlayed: 4, matchesWon: 4, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 5, blocks: 4, effectiveAttacks: 22, mvpCount: 0, ratingAverage: 4.4 },
  },
  {
    id: 'p-vol-7',
    name: 'Diana Solano',
    phone: '+51 911 334 556',
    sport: 'voley',
    position: 'Armador / Colocador (S)',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 2,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 4, matchesWon: 3, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 6, blocks: 2, effectiveAttacks: 10, mvpCount: 0, ratingAverage: 4.3 },
  },
  {
    id: 'p-vol-8',
    name: 'Gonzalo Silva',
    phone: '+51 922 445 667',
    sport: 'voley',
    position: 'Opuesto (OP)',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    skillRating: 5,
    jerseyNumber: 11,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 4, matchesWon: 3, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 10, blocks: 7, effectiveAttacks: 31, mvpCount: 1, ratingAverage: 4.8 },
  },
  {
    id: 'p-vol-9',
    name: 'Luciana Vera',
    phone: '+51 933 556 778',
    sport: 'voley',
    position: 'Central / Bloqueador (MB)',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 8,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 4, matchesWon: 3, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 4, blocks: 11, effectiveAttacks: 15, mvpCount: 0, ratingAverage: 4.4 },
  },
  {
    id: 'p-vol-10',
    name: 'Alexis Fuentes',
    phone: '+51 944 667 889',
    sport: 'voley',
    position: 'Punta Receptor / Atacante (OH)',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    skillRating: 4,
    jerseyNumber: 6,
    isAvailable: true,
    createdAt: '2026-09-28',
    stats: { matchesPlayed: 4, matchesWon: 3, goals: 0, assists: 0, yellowCards: 0, redCards: 0, aces: 7, blocks: 4, effectiveAttacks: 24, mvpCount: 0, ratingAverage: 4.3 },
  },
];

export const DEFAULT_TACTICAL_FORMATIONS: Record<SportType, TacticalFormation[]> = {
  futbol: [
    // 6-Player Formations (Fútbol 6)
    {
      id: 'form-fut-6-221',
      sport: 'futbol',
      name: 'Fútbol 6 (2-2-1)',
      system: '2-2-1',
      slots: [
        { id: 'f6-por', label: 'POR', roleName: 'Arquero', x: 50, y: 88, playerId: 'p-fut-1' },
        { id: 'f6-dfc1', label: 'DFC', roleName: 'Defensa Izq', x: 30, y: 68, playerId: 'p-fut-2' },
        { id: 'f6-dfc2', label: 'DFC', roleName: 'Defensa Der', x: 70, y: 68, playerId: 'p-fut-3' },
        { id: 'f6-mc1', label: 'MC', roleName: 'Medio Izq', x: 32, y: 46, playerId: 'p-fut-4' },
        { id: 'f6-mc2', label: 'MC', roleName: 'Medio Der', x: 68, y: 46, playerId: 'p-fut-5' },
        { id: 'f6-dc', label: 'DC', roleName: 'Delantero', x: 50, y: 18, playerId: 'p-fut-7' },
      ],
    },
    {
      id: 'form-fut-6-131',
      sport: 'futbol',
      name: 'Fútbol 6 (1-3-1)',
      system: '1-3-1',
      slots: [
        { id: 'f6-rom-por', label: 'POR', roleName: 'Arquero', x: 50, y: 88, playerId: 'p-fut-1' },
        { id: 'f6-rom-dfc', label: 'DFC', roleName: 'Líbero Central', x: 50, y: 70, playerId: 'p-fut-2' },
        { id: 'f6-rom-li', label: 'LI', roleName: 'Carrilero Izq', x: 20, y: 46, playerId: 'p-fut-6' },
        { id: 'f6-rom-mc', label: 'MCD', roleName: 'Volante Eje', x: 50, y: 46, playerId: 'p-fut-4' },
        { id: 'f6-rom-ld', label: 'LD', roleName: 'Carrilero Der', x: 80, y: 46, playerId: 'p-fut-5' },
        { id: 'f6-rom-dc', label: 'DC', roleName: 'Delantero', x: 50, y: 18, playerId: 'p-fut-7' },
      ],
    },
    {
      id: 'form-fut-6-212',
      sport: 'futbol',
      name: 'Fútbol 6 (2-1-2)',
      system: '2-1-2',
      slots: [
        { id: 'f6-of-por', label: 'POR', roleName: 'Arquero', x: 50, y: 88, playerId: 'p-fut-1' },
        { id: 'f6-of-dfc1', label: 'DFC', roleName: 'Defensa Izq', x: 30, y: 68, playerId: 'p-fut-2' },
        { id: 'f6-of-dfc2', label: 'DFC', roleName: 'Defensa Der', x: 70, y: 68, playerId: 'p-fut-3' },
        { id: 'f6-of-mc', label: 'MCD', roleName: 'Tapón Central', x: 50, y: 46, playerId: 'p-fut-4' },
        { id: 'f6-of-dc1', label: 'DC', roleName: 'Punta Izq', x: 35, y: 18, playerId: 'p-fut-6' },
        { id: 'f6-of-dc2', label: 'DC', roleName: 'Punta Der', x: 65, y: 18, playerId: 'p-fut-7' },
      ],
    },
    // 7-Player Formations (Fútbol 7)
    {
      id: 'form-fut-7-321',
      sport: 'futbol',
      name: 'Fútbol 7 (3-2-1)',
      system: '3-2-1',
      slots: [
        { id: 's-por', label: 'POR', roleName: 'Arquero', x: 50, y: 88, playerId: 'p-fut-1' },
        { id: 's-li', label: 'LI', roleName: 'Lateral Izq', x: 22, y: 68, playerId: 'p-fut-3' },
        { id: 's-dfc', label: 'DFC', roleName: 'Defensa Central', x: 50, y: 70, playerId: 'p-fut-2' },
        { id: 's-ld', label: 'LD', roleName: 'Lateral Der', x: 78, y: 68 },
        { id: 's-mc1', label: 'MC', roleName: 'Medio Defensivo', x: 35, y: 44, playerId: 'p-fut-4' },
        { id: 's-mc2', label: 'MCO', roleName: 'Medio Creativo', x: 65, y: 44, playerId: 'p-fut-5' },
        { id: 's-dc', label: 'DC', roleName: 'Delantero', x: 50, y: 18, playerId: 'p-fut-7' },
      ],
    },
    {
      id: 'form-fut-7-231',
      sport: 'futbol',
      name: 'Fútbol 7 (2-3-1)',
      system: '2-3-1',
      slots: [
        { id: 's-por-2', label: 'POR', roleName: 'Arquero', x: 50, y: 88, playerId: 'p-fut-1' },
        { id: 's-dfc1-2', label: 'DFC', roleName: 'Central Izq', x: 32, y: 70, playerId: 'p-fut-2' },
        { id: 's-dfc2-2', label: 'DFC', roleName: 'Central Der', x: 68, y: 70, playerId: 'p-fut-3' },
        { id: 's-ei-2', label: 'EI', roleName: 'Extremo Izq', x: 20, y: 42, playerId: 'p-fut-6' },
        { id: 's-mc-2', label: 'MCD', roleName: 'Eje Central', x: 50, y: 48, playerId: 'p-fut-4' },
        { id: 's-ed-2', label: 'ED', roleName: 'Extremo Der', x: 80, y: 42, playerId: 'p-fut-5' },
        { id: 's-dc-2', label: 'DC', roleName: 'Delantero', x: 50, y: 18, playerId: 'p-fut-7' },
      ],
    },
    // 11-Player Formations (Fútbol 11)
    {
      id: 'form-fut-11-433',
      sport: 'futbol',
      name: 'Fútbol 11 (4-3-3)',
      system: '4-3-3',
      slots: [
        { id: 's11-por', label: 'POR', roleName: 'Arquero', x: 50, y: 90, playerId: 'p-fut-1' },
        { id: 's11-li', label: 'LI', roleName: 'Lateral Izq', x: 15, y: 74, playerId: 'p-fut-3' },
        { id: 's11-dfc1', label: 'DFC', roleName: 'Central Izq', x: 38, y: 76, playerId: 'p-fut-2' },
        { id: 's11-dfc2', label: 'DFC', roleName: 'Central Der', x: 62, y: 76 },
        { id: 's11-ld', label: 'LD', roleName: 'Lateral Der', x: 85, y: 74 },
        { id: 's11-mcd', label: 'MCD', roleName: 'Volante Tapón', x: 50, y: 56, playerId: 'p-fut-4' },
        { id: 's11-mc1', label: 'MC', roleName: 'Interior Izq', x: 30, y: 44, playerId: 'p-fut-5' },
        { id: 's11-mc2', label: 'MC', roleName: 'Interior Der', x: 70, y: 44 },
        { id: 's11-ei', label: 'EI', roleName: 'Extremo Izq', x: 20, y: 22, playerId: 'p-fut-6' },
        { id: 's11-dc', label: 'DC', roleName: 'Delantero', x: 50, y: 16, playerId: 'p-fut-7' },
        { id: 's11-ed', label: 'ED', roleName: 'Extremo Der', x: 80, y: 22 },
      ],
    },
  ],
  voley: [
    // 6-Player Volleyball Formations (FIVB Standard Court Positions)
    {
      id: 'form-vol-6-51',
      sport: 'voley',
      name: 'Sistema 5-1',
      system: '5-1',
      slots: [
        // Front Court (Zonas Delanteras 4, 3, 2)
        { id: 'v6-z4', label: 'Z4', roleName: 'Punta Receptor', x: 22, y: 28, playerId: 'p-vol-2' },
        { id: 'v6-z3', label: 'Z3', roleName: 'Central', x: 50, y: 24, playerId: 'p-vol-3' },
        { id: 'v6-z2', label: 'Z2', roleName: 'Opuesto', x: 78, y: 28, playerId: 'p-vol-4' },
        // Back Court (Zonas Zagueras 5, 6, 1)
        { id: 'v6-z5', label: 'Z5', roleName: 'Líbero / Def Izq', x: 22, y: 72, playerId: 'p-vol-5' },
        { id: 'v6-z6', label: 'Z6', roleName: 'Zaguero Centro', x: 50, y: 76, playerId: 'p-vol-6' },
        { id: 'v6-z1', label: 'Z1', roleName: 'Armador (Saque)', x: 78, y: 72, playerId: 'p-vol-1' },
      ],
    },
    {
      id: 'form-vol-6-42',
      sport: 'voley',
      name: 'Sistema 4-2',
      system: '4-2',
      slots: [
        { id: 'v6-42-z4', label: 'Z4', roleName: 'Punta Ataque 1', x: 22, y: 28, playerId: 'p-vol-2' },
        { id: 'v6-42-z3', label: 'Z3', roleName: 'Armador Delantero', x: 50, y: 24, playerId: 'p-vol-1' },
        { id: 'v6-42-z2', label: 'Z2', roleName: 'Punta Ataque 2', x: 78, y: 28, playerId: 'p-vol-4' },
        { id: 'v6-42-z5', label: 'Z5', roleName: 'Líbero Defensivo', x: 22, y: 72, playerId: 'p-vol-5' },
        { id: 'v6-42-z6', label: 'Z6', roleName: 'Defensa Zaguero', x: 50, y: 76, playerId: 'p-vol-6' },
        { id: 'v6-42-z1', label: 'Z1', roleName: 'Armador (Saque)', x: 78, y: 72, playerId: 'p-vol-3' },
      ],
    },
    {
      id: 'form-vol-6-62',
      sport: 'voley',
      name: 'Sistema 6-2',
      system: '6-2',
      slots: [
        { id: 'v6-62-z4', label: 'Z4', roleName: 'Punta Izquierdo', x: 22, y: 28, playerId: 'p-vol-2' },
        { id: 'v6-62-z3', label: 'Z3', roleName: 'Central Rápido', x: 50, y: 24, playerId: 'p-vol-3' },
        { id: 'v6-62-z2', label: 'Z2', roleName: 'Opuesto / Atacante', x: 78, y: 28, playerId: 'p-vol-4' },
        { id: 'v6-62-z5', label: 'Z5', roleName: 'Defensa Izq', x: 22, y: 72, playerId: 'p-vol-5' },
        { id: 'v6-62-z6', label: 'Z6', roleName: 'Líbero Zaguero', x: 50, y: 76, playerId: 'p-vol-6' },
        { id: 'v6-62-z1', label: 'Z1', roleName: 'Armador (Saque)', x: 78, y: 72, playerId: 'p-vol-1' },
      ],
    },
  ],
};

export const INITIAL_MATCHES: MatchEvent[] = [
  {
    id: 'match-fut-next',
    tournamentId: 'tour-fut-1',
    eventName: 'Gran Encuentro de la Fecha 4 - Master League',
    sport: 'futbol',
    homeTeamName: 'Titanes FC (Chaleco Azul)',
    homeTeamLogo: '🛡️',
    homeTeamColor: '#2563eb',
    homePlayerIds: ['p-fut-1', 'p-fut-2', 'p-fut-3', 'p-fut-4', 'p-fut-5', 'p-fut-6', 'p-fut-7'],
    homeFormationId: 'form-fut-6-221',
    
    awayTeamName: 'Huracán Express (Chaleco Rojo)',
    awayTeamLogo: '⚡',
    awayTeamColor: '#dc2626',
    awayPlayerIds: ['p-fut-8', 'p-fut-9', 'p-fut-10', 'p-fut-11', 'p-fut-12'],
    awayFormationId: 'form-fut-6-221',
    
    dateTime: '2026-10-04T19:30',
    venue: 'Estadio Polideportivo Monumental',
    courtNumber: 'Cancha 1 (Césped Sintético FIFA Quality)',
    venueMapQuery: 'Estadio+Monumental+Lima',
    status: 'scheduled',
    tacticalNotes: 'Gran partido del fin de semana. Equipos conformados con los mejores jugadores convocados.',
  },
  {
    id: 'match-vol-next',
    tournamentId: 'tour-vol-1',
    eventName: 'Duelo Estelar de Voleibol 6 vs 6 - Copa Apertura',
    sport: 'voley',
    homeTeamName: 'Vipers Pro (Equipo Morado)',
    homeTeamLogo: '🏐',
    homeTeamColor: '#8b5cf6',
    homePlayerIds: ['p-vol-1', 'p-vol-2', 'p-vol-3', 'p-vol-4', 'p-vol-5', 'p-vol-6'],
    homeFormationId: 'form-vol-6-51',
    
    awayTeamName: 'Smashers (Equipo Naranja)',
    awayTeamLogo: '💥',
    awayTeamColor: '#f97316',
    awayPlayerIds: ['p-vol-7', 'p-vol-8', 'p-vol-9', 'p-vol-10'],
    awayFormationId: 'form-vol-6-51',
    
    dateTime: '2026-10-05T17:00',
    venue: 'Coliseo Polideportivo Central',
    courtNumber: 'Cancha Techada A',
    venueMapQuery: 'Coliseo+Dibos+Lima',
    status: 'scheduled',
    tacticalNotes: 'Sets oficiales a 25 puntos con rotación de 6 posiciones Z1 a Z6.',
  },
  {
    id: 'match-fut-past-1',
    tournamentId: 'tour-fut-1',
    eventName: 'Amistoso de Preparación Fútbol 6',
    sport: 'futbol',
    homeTeamName: 'Titanes FC',
    homeTeamLogo: '🛡️',
    homeTeamColor: '#2563eb',
    homePlayerIds: ['p-fut-1', 'p-fut-2', 'p-fut-3', 'p-fut-4', 'p-fut-5', 'p-fut-6', 'p-fut-7'],
    
    awayTeamName: 'Huracán Express',
    awayTeamLogo: '⚡',
    awayTeamColor: '#dc2626',
    awayPlayerIds: ['p-fut-8', 'p-fut-9', 'p-fut-10', 'p-fut-11', 'p-fut-12'],
    
    dateTime: '2026-09-25T20:00',
    venue: 'Complejo Deportivo El Monumental',
    courtNumber: 'Cancha 1',
    status: 'finished',
    score: {
      homeGoals: 4,
      awayGoals: 2,
      scorers: [
        { playerId: 'p-fut-7', teamSide: 'home', minute: 12 },
        { playerId: 'p-fut-5', teamSide: 'home', minute: 28 },
        { playerId: 'p-fut-7', teamSide: 'home', minute: 44 },
        { playerId: 'p-fut-4', teamSide: 'home', minute: 58 },
      ],
      cards: [
        { playerId: 'p-fut-4', type: 'yellow', minute: 34 },
        { playerId: 'p-fut-2', type: 'yellow', minute: 52 },
      ],
    },
    mvpPlayerId: 'p-fut-5',
    tacticalNotes: 'Gran partido con alta dinámica y contundencia.',
  },
];
